
version: 2

models:
  - name: csvtest_customers
    description: "Table contains customer information."
    columns:
      - name: id
        description: "The primary key for this table"
      - name: name
        description: "The name of the customer"
      - name: email
        description: "The email address of the customer"
  - name: csvtest_orders
    description: "Table contains order information"
    columns:
      - name: id
        description: "The primary key for this table"
      - name: customer_id
        description: "The ID of the customer who placed the order"
      - name: product
        description: "The product that was ordered"
      - name: quantity
        description: "The quantity of the product that was ordered"
